services:
  frontend:
    build: .
    image: zchua040/eduquest-frontend-reactjs:19012026

    ports:
      - "80:80"
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      NEXT_PUBLIC_AZURE_CLIENT_ID: ${NEXT_PUBLIC_AZURE_CLIENT_ID}
      NEXT_PUBLIC_AZURE_REDIRECT_URI: ${NEXT_PUBLIC_AZURE_REDIRECT_URI}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_MICROSERVICE_URL: ${NEXT_PUBLIC_MICROSERVICE_URL}
      NEXT_PUBLIC_LOGIN_REQUEST_SCOPE: ${NEXT_PUBLIC_LOGIN_REQUEST_SCOPE}
